### ISSUE TITLE
bbswitch does not compile on kernel 3.19.0-43 and Ubuntu 14.04.3

### ISSUE THREAD

**Issue by oanonymos0** [Bumblebee-Project/bbswitch#121]
a user reports that he cannot install bbswitch, because it does not compile on kernel 3.19.0-43
and Ubuntu 14.04. See the link for more info:
http://askubuntu.com/questions/719066/problem-installing-bbswitch-on-ubuntu-14-04-3?noredirect=1#comment1063069_719066
I can confirm myself, it does compile on 3.19.0-30. Any solutions/workarounds?

**Comment by ArchangeGabriel** [comment]
The bbswitch version is quite old. Should try with 0.8. Available on our PPA.

**Comment by ArchangeGabriel** [comment]
Forgot that. Just seen it tries 0.8 too.

**Comment by oanonymos0** [comment]
@ArchangeGabriel do you know what could be causing the error?

**Comment by ArchangeGabriel** [comment]
Seems to be on GCC side. I don’t think the error is in bbswitch.

**Comment by Lekensteyn** [comment]
bbswitch is fine, but your disk needs to be replaced. Please continue at https://bugs.launchpad.net/ubuntu/+source/bbswitch/+bug/1532538
