### ISSUE TITLE
module bbswitch is not loaded automatically at startup

### ISSUE THREAD

**Issue by shankarregmi** [Bumblebee-Project/bbswitch#122]
Dell Inspirion N5110/Nvidia GeForce GT-525M

I have installed bbswitch kernel module to turn off the optimus chip which is give me a headache.
But on every restart I need to manually do following
`# modprobe -r nouveau //unload nouveau driver`
`tee /proc/acpi/bbswitch <<<OFF` // to turn off the card

still I have config on `/etc/modules` 
  `bbswitch load_state=0`
and on `/etc/modprobe.d/bbswitch.conf`
  `options bbswitch load_state=0`

**Comment by ArchangeGabriel** [comment]
You closed this, so I don’t know whether you’ve solved your issue or not, but in case anyone come across this, you have to explicitly load bbswitch module on start (using modprobe either at initramfs or system level) and blacklist nouveau.

But you might also note that just letting nouveau handle PM should be fine, you don’t need bbswitch for this.
