### ISSUE TITLE
Installing linux (4.5-1) breaks dependency 'linux<4.5'

### ISSUE THREAD

**Issue by friederbluemle** [Bumblebee-Project/bbswitch#127]
Cannot automatically update Arch to the latest with bbswitch installed.

    looking for conflicting packages...
    error: failed to prepare transaction (could not satisfy dependencies)
    :: bbswitch: installing linux (4.5-1) breaks dependency 'linux<4.5'

**Comment by Lekensteyn** [comment]
You apparently have the testing repository enabled, but then you also have to enable community-testing in /etc/pacman.conf.

**Comment by friederbluemle** [comment]
@Lekensteyn That was it. Thanks! And sorry for erroneously opening an issue.
