### ISSUE TITLE
Eurocom M5 Pro draining 40% of battery per hour while suspended to ram

### ISSUE THREAD

**Issue by JeorgeMatt** [Bumblebee-Project/bbswitch#129]
I recently decided to use Ubuntu as my main OS in Eurocom M5 Pro, but I have noticed something strange with bbswitch.
After installing it is draining a way too much battery while suspended to run. In windows or without bbswitch it uses about 3% per hour.
Everything is working perfectly but the system is impossible to use as a laptop since the suspend to ram  does not last very long and the hibernation is unreliable.

Is there any fix for this?

**Comment by oanonymos0** [comment]
having an open OpenGL program on nvidia before suspend may help.

**Comment by Lekensteyn** [comment]
I think this is a duplicate of #115, if not please let me know.

**Comment by JeorgeMatt** [comment]
It is a different laptop and i'm not sure if it is the same problem
