### ISSUE TITLE
Acer Aspire 5820TG graphics not supported

### ISSUE THREAD

**Issue by razr69** [Bumblebee-Project/bbswitch#133]
I tried to enable bbswitch on my _Acer Aspire 5820TG_. As stated at [notebookcheck.net](http://www.notebookcheck.net/Review-Acer-Aspire-5820TG-Notebook.38343.0.html) it uses _an ATI GPU, the Mobility Radeon HD5650, or an Intel GMA HD graphics solution, incorporated in the Intel CPU_.

When I try to enable the module it says:
```
[root@notebook ~]# modprobe bbswitch load_state=0 unload_state=1
[XXX] bbswitch: No suitable _DSM call found.
modprobe: ERROR: could not insert ´bbswitch´: No such device
```

Here some infos on my system:
```
[user@notebook ~]$ uname -r
4.6.2-1-ARCH
[user@notebook ~]$ pacman -Q bbswitch
bbswitch 0.8-50
[user@notebook ~]$ lspci | grep VGA
01:00.0 VGA compatible controller: Advance Micro Devices, Inc. [AMD/ATI] Madison [Mobility Radeon HD 5650/5750 / 6530M/6550M]
```

If there is any more information I can provide I'll be happy to do so.

**Comment by ArchangeGabriel** [comment]
Hi, we don’t support AMD/ATI hybrid setups (PowerXpress) at all. But FWIK, it should work seemlessly with PRIME at least.
