### ISSUE TITLE
nvidia card remains ON after stopping primusrun

### ISSUE THREAD

**Issue by nikonikolov** [Bumblebee-Project/bbswitch#136]
Might be a long shot, but it would be really nice if bbswitch automatically turns OFF the nvidia card after it stops being used. Right now I have to unload all nvidia kernel modules and manually stop the card with `sudo tee /proc/acpi/bbswitch <<<OFF`.

**Comment by Lekensteyn** [comment]
This (unloading modules and triggering bbswitch) is something that Bumblebee should do. As bbswitch is just a building block, it won't do this.

Please try the develop branch of Bumblebee and install an apropriate modprobe.conf line that also removed nvidia-uvm, etc. on unload.
