### ISSUE TITLE
dGPU unusable after suspend

### ISSUE THREAD

**Issue by eke2152** [Bumblebee-Project/bbswitch#143]
I have a Asus laptop specs:
i5-6200u, 940mx, realtek rtl8723 wifi-card

I tried with kernel 4.4, 4.8 and 4.9rc3, fedora, ubuntu and manjaro.
Computer runs ok with bumblebee and nvidia-prime but after suspend-resume dGPU becomes unusable. Bbswitch cannot change dGPU power state cat /proc/acpi/bbswitch says OFF but there is this line in the dmesg: "[ 2581.501737] pci 0000:01:00.0: Refused to change power state, currently in D0"

Ubuntu 16.04 kernel 4.4:
with nvidia-prime:
-PC works ok with dGPU
-Suspend & resume -> freeze
with bumblebee:
-PC works ok with primusrun.
-Suspend & resume -> bumblebee says NVIDIA GPU couldn't initialized but system works ok.

Fedora 25 kernel 4.8:
with nouveau:
-DRI_PRIME=1 glxgears -> works ok
-Suspend & resume -> DRI_PRIME=1 glxgears -> whole system freezes.

Also i have another problem too but im not sure its related. realtek wifi card giving pcie aer correctable errors flooding dmesg (i use pci=noaer as a workaround functionally no problem.) after suspend&resume these messages go away.
[ASUSTeK_COMPUTER_INC.-X555UQ.tar.gz](https://github.com/Bumblebee-Project/bbswitch/files/575347/ASUSTeK_COMPUTER_INC.-X555UQ.tar.gz)

**Comment by Lekensteyn** [comment]
Try to boot with `acpi_osi=! acpi_osi="!Windows 2009"`, otherwise the power might not be restored as you have noticed. No idea about the Wi-Fi card.

Possibly related: #134

**Comment by eke2152** [comment]
acpi_osi workaround doesn't work in my case. I noticed something that if i unplug powercord when sleep state computer shuts off. (Both in windows 10 & linux) I dont know if this is expected behaviour with new laptops.

**Comment by Lekensteyn** [comment]
Complete shutdown when unplugging power cord sounds like a firmware issue. Have you looked for a BIOS update?

**Comment by eke2152** [comment]
There is no bios update however i re-flashed same BIOS and shutdown problem solved but other issues remaining so should i attach another acpidump in case something changed with re-flash?

**Comment by Lekensteyn** [comment]
It is worth creating a new acpidump and check for differences (just `acpidump.txt` is sufficient if the dmidecode output did not change). Re-flashing your BIOS has possibly reverted some changes to their defaults.

**Comment by eke2152** [comment]
Sorry i couldn't reply earlier so i think im getting somewhere. Latest bios Update description says update nv vbios so when i reflashed bios there is a line in bios settings showing nv vbios version but after booting linux

Suspend resume --> freeze poweroff from button

And nv vbios line from bios is gone. After that pc power off instead of sleeping when in battery.
So in linux nvidia vbios somehow deleted from bios (is this possible?)

My understanding is that i have a device specific vbios and in linux nvidia driver loads its generic vbios and this causing problem so this is unrelated to bbswitch. I am closing this

**Comment by Lekensteyn** [comment]
Hm, can you also reproduce the issue after full shutdown instead of reboot? Rebooting might be diifferent from shutdown.

**Comment by eke2152** [comment]
Yes reboot and full shutdown same issue but i think this is related to the prop drivers when using nouveau system freezes after suspend but there is no bios issue.
