### ISSUE TITLE
Powertop --auto-tune: Refused to change power state

### ISSUE THREAD

**Issue by postadelmaga** [Bumblebee-Project/bbswitch#159]
Kernel: 4.12.10-1-ARCH
Nvidia: 01:00.0 3D controller: NVIDIA Corporation GM108M [GeForce 940MX] (rev ff)
Driver: Nvidia 384.69

`powertop --auto-tune` makes Nvidia card not usable on battery 

**How to replicate:**
1. Execute `powertop --auto-tune`  OR `echo  'auto' > '/sys/bus/pci/devices/0000:01:00.0/power/control';`
2. unplug the power and run on battery
3. `sudo tee /proc/acpi/bbswitch <<<ON and then cat /proc/acpi/bbswitch`
4. Try to run any app with `optirun` ... fails

* This is what I see in dmesg:
`pci 0000:01:00.0: Refused to change power state, currently in D3`
* Plug in the power again OR revert the PM setting (`echo  'on' > '/sys/bus/pci/devices/0000:01:00.0/power/control';`), don't solve the issue but I need to reboot the system: 

Another user reported same issue here:
https://github.com/Bumblebee-Project/bbswitch/issues/140#issuecomment-283809440

**Comment by Lekensteyn** [comment]
It is the same problem as #140. You must not enable runtime PM for the Nvidia device *or* alternatively boot with the `pcie_port_pm=off` option as described in #140.
