### ISSUE TITLE
Allow switching bios to discrete card on next reboot

### ISSUE THREAD

**Issue by norbusan** [Bumblebee-Project/bbswitch#19]
Hi everyone,
first of all thanks a lot for your work on that. I have myself maintained a bit of time the special sony-laptop-zseries module [1], a replacement for the in-kernel sony-laptop module, to allow switching between graphics cards.

Most of the added functionality that was in the sony-laptop-zseries modules has now been included in the development branch of sony-laptop [2], but not all, namely the discrete gpu switching. For that I was planning to use bbswitch.

Unfortunately, it seems that the inner workings of my laptop (Sony Z11 old series VGN-Z11) and many others are a bit different. We have a hardware switch Stamina-Speed, which is now also recognized by the sony-laptop module and exported as acppi event.

Using bbswitch I can turn on and off the nvidia card, but the actual graphic output cannot be switched by that, or at least I haven't found out how. The terminal, the kernel, always boots into intel graphics mode.

To give you an idea how it worked before:
* I added acpi_osi=\"!Windows 2006\" to the kernel boot parameter: this is essential (as far as I know)
* then, when turning the speed-stamina switch to speed or stamina resp, on the next reboot already the bios worked with the respective card, thus also linux of course.
* When I keep this parameter and boot up into linux the nvidia card is *completely* disabled, i.e., does not show up in the lspci, nor can bbswitch find it

I tried unloading the module with the unload_state set to 1, but that didn't help either.

It would be great if one could switch on/off the actual output of the card, too.

Here the additional information as requested:

```
[   21.380889] bbswitch: version 0.4.2
[   21.382324] bbswitch: Found integrated VGA device 0000:00:02.0: \_SB_.PCI0.OVGA
[   21.383784] bbswitch: Found discrete VGA device 0000:01:00.0: \_SB_.PCI0.PEGP.DGPU
[   21.385352] bbswitch: detected a nVidia _DSM function
[   21.386769] bbswitch: Succesfully loaded. Discrete card 0000:01:00.0 is on
...
[  124.713535] usbcore: registered new interface driver btusb
[  176.484079] usb 8-2: USB disconnect, device number 2
[  206.200313] bbswitch: disabling discrete graphics
[  206.216082] pci 0000:01:00.0: power state changed by ACPI to D3
[  206.230006] bbswitch: Result of _DSM call for OFF: 00000000
```

```
uname -a
Linux mithrandir 3.4.0+ #68 SMP PREEMPT Mon May 21 22:35:57 JST 2012 x86_64 GNU/Linux
```

Debian/unstable up to date, kernel build from git

xserver-xorg: 1:7.6+13 (Debian)
from xorg.0.log: X.Org X Server 1.12.1.902 (1.12.2 RC 2)
module intel: compiled for 1.12.1, module version = 2.18.0

```
/proc/acpi/dump_info:
0000:00:00.0 060000 
0000:00:01.0 060400 \_SB_.PCI0.PEGP
0000:00:02.0 030000 \_SB_.PCI0.OVGA
0000:00:19.0 020000 \_SB_.PCI0.LANC
0000:00:1a.0 0c0300 \_SB_.PCI0.UHC3
0000:00:1a.1 0c0300 \_SB_.PCI0.UHC4
0000:00:1a.2 0c0300 \_SB_.PCI0.UHC5
0000:00:1a.7 0c0320 \_SB_.PCI0.EHC2
0000:00:1b.0 040300 
0000:00:1c.0 060400 \_SB_.PCI0.EXP1
0000:00:1c.1 060400 \_SB_.PCI0.EXP2
0000:00:1c.3 060400 \_SB_.PCI0.EXP4
0000:00:1d.0 0c0300 \_SB_.PCI0.UHC0
0000:00:1d.1 0c0300 \_SB_.PCI0.UHC1
0000:00:1d.2 0c0300 \_SB_.PCI0.UHC2
0000:00:1d.7 0c0320 \_SB_.PCI0.EHC1
0000:00:1e.0 060401 \_SB_.PCI0.P32_
0000:00:1f.0 060100 \_SB_.PCI0.LPC_
0000:00:1f.2 010601 \_SB_.PCI0.SAT0
0000:00:1f.3 0c0500 \_SB_.PCI0.SBUS
0000:01:00.0 030000 \_SB_.PCI0.PEGP.DGPU
0000:06:00.0 028000 \_SB_.PCI0.EXP2.WLAN
0000:0b:04.0 060700 \_SB_.PCI0.P32_.CBC0
0000:0b:04.1 0c0010 
0000:0b:04.2 080500 
0000:0b:04.4 088000 
```

Links
[1] sony-laptop-zseries adapted module code: http://gitorious.org/sony-laptop-zseries/sony-laptop-zseries/blobs/master/sony-laptop.c
[2] kernel driver development tree for sony-laptop: http://git.kamineko.org/cgi-bin/gitweb.cgi?p=linux-sony-2.6.git;a=summary

**Comment by ArchangeGabriel** [comment]
@norbusan Three year and a half later, what is the situation here? :)

**Comment by norbusan** [comment]
Umpf, sorry, I don't have that laptop anymore, thus I am closing this issue.
