### ISSUE TITLE
Acer Aspire 5745g: No Suitable _DSM call found

### ISSUE THREAD

**Issue by furiousbean** [Bumblebee-Project/bbswitch#4]
[    6.629192] bbswitch: Found discrete VGA device 0000:01:00.0: _SB_.PCI0.P0P2.PEGP
[    6.629283] bbswitch: No suitable _DSM call found.

Linux bean_laptop 3.1.7-1-ARCH #1 SMP PREEMPT Wed Jan 4 08:11:16 CET 2012 x86_64 Intel(R) Core(TM) i5 CPU M 430 @ 2.27GHz GenuineIntel GNU/Linux

Arch Linux

01:00.0 VGA compatible controller: nVidia Corporation GT218 [GeForce 310M](rev a2)

Neither nouveau nor nvidia driver was loaded.

```
cat /proc/acpi/dump_info
0000:00:00.0 
0000:00:01.0 \_SB_.PCI0.P0P2
0000:00:02.0 \_SB_.PCI0.GFX0
0000:00:16.0 
0000:00:1a.0 \_SB_.PCI0.EHC2
0000:00:1b.0 \_SB_.PCI0.HDEF
0000:00:1c.0 \_SB_.PCI0.RP01
0000:00:1c.5 
0000:00:1d.0 \_SB_.PCI0.EHC1
0000:00:1e.0 \_SB_.PCI0.P0P1
0000:00:1f.0 \_SB_.PCI0.LPCB
0000:00:1f.2 \_SB_.PCI0.AHCI
0000:00:1f.3 \_SB_.PCI0.SBUS
0000:00:1f.6 
0000:01:00.0 \_SB_.PCI0.P0P2.PEGP
0000:01:00.1 \_SB_.PCI0.P0P2.PEGA
0000:02:00.0 \_SB_.PCI0.RP01.PXSX
0000:03:00.0 
0000:3f:00.0 
0000:3f:00.1 \_SB_.CPBG.IMCH
0000:3f:02.0 
0000:3f:02.1 
0000:3f:02.2 
0000:3f:02.3 
```

Link to ACPI information:
http://dl.dropbox.com/u/57246352/Acer-Aspire_5745G.tar.gz

**Comment by Lekensteyn** [comment]
Do you still have this laptop? While developing a new version I found this special case which might not be needed.

There is a `\_SB.PCI0.P0P2.PEGP._DSM` method which calls `\_SB.PCI0.GFX0._DSM` (which calls `\_SB.PCI0.P0P2.PEGP.NVOP`) when the global "OTMS" flag is set. Apparently your BIOS has a [Graphic mode][1] option (Switchable / Discrete). Can you verify whether the PEGP handle is detected when you set your Graphic mode option to Switchable?

 [1]: https://www.bios-mods.com/forum/Thread-REQUEST-Acer-Aspire-5745G
