### ISSUE TITLE
bumblebee-git will not work on linux-mainline kernel 

### ISSUE THREAD

**Issue by ryanvade** [Bumblebee-Project/bbswitch#80]
Hello everyone, 
I have installed both linux-mainline and bumblebee-git on Arch Linux for my GT 630m. When I use optirun I get the Daemon not running and no socket error, at least when using the 3.13. kernel.  However, when I use the 3.12.5 kernel I don't have these issues. 

I can just use the stable kernel yes, but the 3.13 kernel has HUGE wireless improvements that help my laptop. (with an Intel 7260 AC NIC).  

Is this issue #75 
Any suggestions?

**Comment by ArchangeGabriel** [comment]
I’m closing this. The main issue was incompatibilities between nvidia driver and latest kernel. If anyone is still having troubles after all this time, please open a new thread.
