### ISSUE TITLE
bbswitch crashes Asus UX32LN, NVidia GeForce 840M

### ISSUE THREAD

**Issue by shipilev** [Bumblebee-Project/bbswitch#97]
Hi, I have Asus UX32LN, which seems to have NVidia 840M:
`03:00.0 3D controller: NVIDIA Corporation GM108M [GeForce 840M] (rev ff)`

Running Xubuntu 12.04 with:

`Linux shade-laptop 3.13.0-36-generic #63-Ubuntu SMP Wed Sep 3 21:30:07 UTC 2014 x86_64 x86_64 x86_64 GNU/Linux`

...loading bbswitch via `/etc/modules`, and forcing `load_state=0` through `/etc/modprobe.d/`.

bbswitch really helps to cut down the power consumption there (my estimate it saves around 3W), but it seems to sporadically crash the system. When the crash happens, it happens at least on two consecutive boots. Today, it happened >10 boots in the row. After the kernel boots, the crash happens within ~5-20 seconds. Sometimes I see a snow-crash shortly before system shuts down, sometimes it just shuts down silently. After I managed to comment out `load_state=0` from modprobe.d, the crash carousel stopped.

Remarkably, after I echoed "OFF" to `/proc/acpi/bbswitch`, the NVidia card seem to be turned off nicely, as far as I can tell from power consumption, and no crash was observed for at least 30 minutes now. I'll keep a watch on this. Any pointers how to debug this issue would be appreciated. The crash leaves no trace in the system logs...

For the record, my kernel options do stuff with ACPI: `quiet splash pcie_aspm=force drm.vblankoffdelay=1 i915.semaphores=1 acpi_osi=`, which may be contributing to this?

**Comment by ArchangeGabriel** [comment]
Yes, `pcie_aspm=force` can leads to severe issues, and moreover shouldn’t be needed for anyone with not outdated kernels.
